---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
      affinity:
        podAntiAffinity:                                 
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:                               
              matchLabels:                               
                networkservicemesh.io/impl: "simple-endpoint" 
metadata:
  name: "simple-client"
  namespace: default
  annotations:
    ns.networkservicemesh.io: icmp-responder?app=simple-client
