---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: service-chain
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: proxy
      route:
        - destination:
          destinationSelector:
            app: router1
            device : router1
    - match:
      sourceSelector:
        link: r1-r2
      route:
        - destination:
          destinationSelector:
            app: firewall
    - match:
      sourceSelector:
        app: firewall
      route:
        - destination:
          destinationSelector:
            app: gateway
