---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: topo
  namespace: default
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        link: r1-r2
      route:
        - destination:
          destinationSelector:
            device: router2
